services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      MYSQL_TCP_PORT: ${TYPEORM_PORT}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${TYPEORM_DATABASE}
      MARIADB_USER: ${TYPEORM_USERNAME}
      MARIADB_PASSWORD: ${TYPEORM_PASSWORD}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8090:8080
