export enum DatabaseTypes {
    VarChar = 'varchar',
    Int = 'int',
    BigInt = 'bigint',
    TinyInt = 'tinyint',
    Text = 'text',
    Date = 'date',
    DateTime = 'datetime',
    LongText = 'longtext',
    Numeric = 'numeric',
    Decimal = 'decimal',
    Geometry = 'geometry',
    Char = 'char',
    Enum = 'enum',
}
